apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: backups.kentledge.deltachaos.de
spec:
  group: kentledge.deltachaos.de
  names:
    kind: Backup
    listKind: BackupList
    plural: backups
    singular: backup
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      subresources:
        status: {}
      schema:
        openAPIV3Schema:
          type: object
          properties:
            apiVersion:
              type: string
            kind:
              type: string
            metadata:
              type: object
            spec:
              type: object
              properties:
                schedule:
                  type: string
                  description: "Cron schedule for the backup"
                clusterBackupStore:
                  type: object
                  properties:
                    name:
                      type: string
                targets:
                  type: array
                  items:
                    type: object
                    properties:
                      type:
                        type: string
                      name:
                        type: string
                      url:
                        type: string
                        nullable: true
                      matchLabel:
                        type: object
                        properties:
                          app:
                            type: string
      additionalPrinterColumns:
        - name: Schedule
          type: string
          jsonPath: .spec.schedule
        - name: Cluster Backup Store
          type: string
          jsonPath: .spec.clusterBackupStore.name
        - name: Targets
          type: string
          jsonPath: .spec.targets[*].name
