{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kentledge.fullname" . }}
  labels:
{{ include "kentledge.labels" . | indent 4 }}
rules:
  - apiGroups: [""]
    resources: ["*"]
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
{{- end -}}
