apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: clusterbackupstores.kentledge.deltachaos.de
spec:
  group: kentledge.deltachaos.de
  names:
    kind: ClusterBackupStore
    listKind: ClusterBackupStoreList
    plural: clusterbackupstores
    singular: clusterbackupstore
  scope: Cluster
  versions:
    - name: v1alpha1
      served: true
      storage: true
      subresources:
        status: {}
      schema:
        openAPIV3Schema:
          type: object
          properties:
            apiVersion:
              type: string
            kind:
              type: string
            metadata:
              type: object
            spec:
              type: object
              properties:
                borgBackupServer:
                  type: object
                  properties:
                    url:
                      type: string
                    credentials:
                      type: object
                      properties:
                        username:
                          type: string
                        password:
                          type: string
                storageClass:
                  type: string
                  description: "Optional storage class for temporary volumes, defaults to emptydir"
                  nullable: true
                retentionPolicy:
                  type: object
                  properties:
                    keepDaily:
                      type: integer
                    keepWeekly:
                      type: integer
                    keepMonthly:
                      type: integer
